### PR TITLE
add ghci container

### PR DESCRIPTION
**Pull request by mahf708**
adds github-action ci container. 

The ghci container is mainly for testing on github actions:
- the container is based on spack/ubuntu-jammy:0.22.1
- the container relies on binary cache to accelerate builds
- the container is based on gcc 11, native to ubuntu 22.04 (jammy)
- the container has mpich 3.4.3, to ensure compatibility with craympich
- the container houses within it (~10 GB of) data files from the inputdata server

The github actions workflow added in this PR (.github/workflows/ghci.yaml):
- it checks out the code recursively (in case we add e3sm as a submod here), it logs in into the gh container registry (ghcr), it then builds (requiring QEMU, etc.) the container, and pushes if it is not a PR
- it is designed such that it is unique for each container (containers-ghci is the name of the container, and its versioning will follow ghci-0.1.0; so for abcd container, it will be containers-abcd with abcd-1.2.3)
- the action is guarded such that it only runs if the files added in this PR are edited later or if there's a tag with "ghcr" in it

### CODE REVIEW

**Comment by mahf708** [comment]
cc @ndkeen @bartgol on adding a container in this repo. 

@rljacob, I am going to merge today if I don't hear from you, hope that's okay :)

**Comment by rljacob** [comment]
Can you describe what the github action in this PR does?

**Review by rljacob — APPROVED** [review]

**Review by bartgol — APPROVED** [review]
Is the action simply building the image and pushing it to the registry?

**Comment by mahf708** [comment]
> Can you describe what the github action in this PR does?

> Is the action simply building the image and pushing it to the registry?

Yes, the action builds the Dockerfile, then pushes it to the github container registry (ghcr). If we want, we can add one step to also push to Docker registry (docker hub). Note that the step called "Push" takes care of both building and pushing, but it doesn't actually push if it is in a PR. Additionally, the action has all sorts of guards to make it only push when these files are edited, and it will push containers with a distinct signature (so that they don't conflict with other containers). The metadata step gathers automated information about the container so that they can be automatically added to the image (like version, sha, etc.).

I will add a description to the PR post (and the commit message) before merging.

**Pull request merged**
